name: test-deploy

# Run this on tests of new PRs
on:
  pull_request:
    branches-ignore:
      - main
    paths:
    - piximi-documentation/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install jupyter-book

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build piximi-documentation/
